# Generated by Django 4.2.5 on 2023-12-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0004_alter_cruise_destinations_inforequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.TextField(max_length=2000)),
            ],
            options={
                'db_table': 'relecloud_opinions',
            },
        ),
    ]
