# Generated by Django 4.2.5 on 2023-12-19 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0005_opinions'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='opinions',
            table='relecloud_opinions',
        ),
    ]
