# Generated by Django 4.2.5 on 2023-12-18 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0005_opinions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Opinions',
        ),
    ]
