# Generated by Django 4.2.5 on 2023-12-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0006_delete_opinions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.TextField(max_length=2000)),
            ],
            options={
                'db_table': 'relecloud_opinions',
            },
        ),
    ]
