# Generated by Django 4.2.5 on 2023-12-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0007_opinions'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(default='images/imagenDefault.jpg', upload_to='images/'),
        ),
    ]
